--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/thebigcrafter/KygekEasyGamemode
build-by-default: true
branches:
- main
projects:
  KygekEasyGamemode:
    path: ""
    libs:
    - src: thebigcrafter/Hydrogen/Hydrogen
      version: ^1.0.0
...
