---
# A PocketMine-MP plugin to quickly change gamemodes
# Copyright (C) 2020 Kygekraqmak
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

name: KygekEasyGamemode
main: Kygekraqmak\KygekEasyGamemode\Main
api: 3.0.0
version: 1.0.0
author: Kygekraqmak

commands:
  gmdc:
    description: Change gamemode to Creative
    permission: kygekeasygmd.gmdc
    usage: "/gmdc [player]"
  gmds:
    description: Change gamemode to Survival
    permission: kygekeasygmd.gmds
    usage: "/gmds [player]"
  gmda:
    description: Change gamemode to Adventure
    permission: kygekeasygmd.gmda
    usage: "/gmda [player]"
  gmdsp:
    description: Change gamemode to Spectator
    permission: kygekeasygmd.gmdsp
    usage: "/gmdsp [player]"

permissions:
  kygekeasygmd.gmdc:
    description: Permission to use /gmdc for self and other
    default: op
  kygekeasygmd.gmdc.self:
    description: Permission to use /gmdc for self
    default: op
  kygekeasygmd.gmdc.other:
    description: Permission to use /gmdc for other
    default: op
  kygekeasygmd.gmds:
    description: Permission to use /gmds for self and other
    default: op
  kygekeasygmd.gmds.self:
    description: Permission to use /gmds for self
    default: op
  kygekeasygmd.gmds.other:
    description: Permission to use /gmds for other
    default: op
  kygekeasygmd.gmda:
    description: Permission to use /gmda for self and other
    default: op
  kygekeasygmd.gmda.self:
    description: Permission to use /gmda for self
    default: op
  kygekeasygmd.gmda.other:
    description: Permission to use /gmda for other
    default: op
  kygekeasygmd.gmdsp:
    description: Permission to use /gmdsp for self and other
    default: op
  kygekeasygmd.gmdsp.self:
    description: Permission to use /gmdsp for self
    default: op
  kygekeasygmd.gmdsp.other:
    description: Permission to use /gmdsp for other
    default: op
...
